[package]
name = "pmi-data-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.4"
sqlx = { version = "0.8.6", features = ["runtime-tokio-native-tls", "postgres", "chrono", "uuid"] }
tokio = { version = "1.45.1", features = ["full"] }
